baseURL = "https://nao50.github.io/hugo-devdoc/"
languageCode = "en-us"
title = "Home"
enableGitInfo = true
pygmentsCodeFences = true
theme = "hugo-devdoc"
canonifyurls = true

[taxonomies]
  category = "categories"
  level = "level"
[blackfriday]
  fractions = false

